<?php if (!defined('APPLICATION')) exit();
// DO NOT EDIT THIS FILE
// All of the settings defined here can be overridden in the /conf/config.php file.

$Configuration['Pages']['Custom']['AllowPHP'] = true;
$Configuration['Pages']['Custom']['DefaultExtension'] = '';
